### ISSUE TITLE
나머지 모델에 대한 CRUD 구현

### ISSUE THREAD

**Issue by sanghunjo921** [f-lab-edu/realtor#12]
### 목표

[REST API Spec](https://www.notion.so/REST-API-Specification-35c6dd354a424607a65a638e98505df4?pvs=4)에서 아래 엔드포인트에 해당하는 API를 구현합니다.

'application'
- GET /users/{userId}/applications/
- POST /users/{userId}/applications/
- PUT/ users/{userId}/applications/{applicationId}/
- DELETE/ users/{userId}/applications/{applicationId}/

'contract'
- GET /agents/{agentId}/contracts/{contractId}/
- GET /agents/{agentId}/contracts/
- POST /agents/{agentId}/contracts/
- PUT/ agents/{agentId}/application/{contractId}/
- DELETE/ agents/{agentId}/application/{contractId}/

'preferredPropertiy'
- GET /users/{userId}/preferredProperties/
- POST /users/{userId}/preferredProperties/
- PUT /users/{userId}/preferredProperties/{preferredPropertiesId}/
- DELETE /users/{userId}/preferredProperties/{preferredPropertiesId}/

'user'
- GET /users/{userId}/
- POST /users/{userId}/
- PUT /users/{userId}/
- DELETE /users/{userId}/

'agent'
- GET /agents/
- GET /agents/{agentId}/
- POST /agents/
- PUT /agents/{agentId}/
- DELETE /agents/{agentId}/

### 제약 조건

- 각 엔드포인트 구현에 ViewSet을 사용하지 않습니다.
- Django REST Framework의 라우터를 사용하지 않고 위의 엔드포인트를 dispatch할 수 있도록 각 컴포넌트의 urls 파일을 수정해야 합니다. 

### 태스크

- [ ]  이미 구현된 Property의 serializers.py의 참조하여 각 모델에 대한 serializer를 정의합니다.
- [ ] 이미 구현된 Property의 views.py를 참조하여 적절한 generic view를 생성합니다. 이렇게 생성한 view들과 구현된 Property의 urls.py를 참조하여 urls.py를 수정합니다.

### 통과조건 (Acceptance Criteria)
- Postman을 통해 각 엔드포인트를 호출 시 기대했던 결과를 반활할 것.

**Comment by sanghunjo921** [comment]
user 모델에서 views.py 작업중인데 post method를 날릴때 users/{userid} OR users/인지 고민했습니다.

처음에는 유저가 계정 생성할때 다른 유저들의 정보를 볼 필요가 없어서 users/{userid}인거 같았는데 생각해보니까 생성 부분에서 post requst를 날리니까 users/가 맞는거 같습니다.

그리고 이슈 만들때 get reqeust에 대해 users/{userid}부분만 생각해봤는데 어드민이 존재한다면 전체 유저를 모니터링하기 위해 users/부분도 필요할꺼 같아서 추가했습니다.

**Comment by sanghunjo921** [comment]
users의 urls.py 부분이 현재 고민이긴한데 저가 모델을 컴포넌트별로 나눌때 users안에 user & agent모델을 넣어놨는데 이렇게 하면 루트에서 "users/", include(users.urls)를 하고 유저 부분에서 urls 를 유저와 에이전트별로 두개로 만들지 생각하고 있습니다.

**Comment by f-lab-stephen** [comment]
> user 모델에서 views.py 작업중인데 post method를 날릴때 users/{userid} OR users/인지 고민했습니다.
> 
> 처음에는 유저가 계정 생성할때 다른 유저들의 정보를 볼 필요가 없어서 users/{userid}인거 같았는데 생각해보니까 생성 부분에서 post requst를 날리니까 users/가 맞는거 같습니다.
> 
> 그리고 이슈 만들때 get reqeust에 대해 users/{userid}부분만 생각해봤는데 어드민이 존재한다면 전체 유저를 모니터링하기 위해 users/부분도 필요할꺼 같아서 추가했습니다.

아주 좋습니다! 그런 식으로 실제로 구현하면서 스펙의 어떤 부분에 문제가 있었는지 보완하는 것이 필요합니다. 수정된 내용은 스펙에도 반영해 주시고요.

말씀해 주신 대로, 만약 User 모델이 일반적인 DB 모델이라면 여기에 대한 POST는 users/ 엔드포인트에서 해야 합니다. ID는 서버 쪽에서 지정해 주기 때문에 생성 전에는 어떤 ID 값을 가지게 될지를 모르기 때문입니다.

다만 나중에 로그인 부분을 구현하면서 해당 부분은 필요 없어질 가능성이 높습니다. 예를 들면, SignUpView, RegisterView 등의 이름으로 회원가입을 시키게 될 것이기 때문입니다.

**Comment by sanghunjo921** [comment]
현재 agent가 user로부터 상속받고 있는데 user랑 agent가 충돌이 나는거 같네요.
일단 포스트맨 테스트 결과 유저 테이블에 존재하는 이름으로 agent를 못만드는 버그가 존재하네요. user를 abstractuser로 만들었는데 이름 필드 자체를 따로 만들어야 할꺼 같긴한데 두 테이블간의 충돌을 어찌할지 고민입니다.

abstractUser를 상속받는 user 테이블 밑으로 general user와 agent를 따로 나누어서 관리하는건 괜찮은가요?

**Comment by sanghunjo921** [comment]
> 사실 문제가 되는 부분은 모델의 상속 그 자체입니다. 장고에서 모델의 상속하기 위한 방법으로 어떤 것이 있는지 (hint: 세 가지), 각각의 장단점이 무엇인지, 어떤 것이 원하는 것을 구현하기 위해 best인지 생각해 보세요. @sanghunjo921

옙 일단 상속부분을 고쳐야겠네요!

**Comment by sanghunjo921** [comment]
### **상속 방법 3 가지** 

1. abstract base classes
- 부모 클래스(abstract=True)를 통해 하위 모델에 일일이 정보를 입력하지 않기 위해 사용. 즉 몇 가지 공통된 정보를 여러 모델에 넣을때 사용 but 디비 하위 모델 당 하나의 테이블만 생성. 즉 부모 모델은 물리적으로 존재하지 않는 가상의 클래스가 되며 자식 모델들이 실체화. 
2. multi table inheritance
- 기존 모델을 하위 클래스화하고 각 모델이 자체 디비 테이블을 가질 수 있음
3. proxy model 
- 이미 존재하는 모델을 그대로 받아들이면서 새로운 기능을 추가. 인스턴스를 생성, 삭제 및 업데이트 가능하며 기존의 모델을 사용하는 것 처럼 모든 데이터가 저장된다. (proxy=true)

=> 첫 번째 방법을 사용할 경우 공통된 필드를 가진 부모 클래스를 만들고 부모클래스는 독립적으로 사용 불가능 하기에 이로부터 상속받는 user & agent가 필요하다.
=> 멀티 테이블 상속시 각 모델에 대해 매칭되는 테이블이 생성된다 하지만 자식 테이블에 대한 각 쿼리에 대해 부모 테이블로의 조인이 필요하므로 부하가 발생
=> 마지막 방법의 경우 모델의 필드를 변경할 수 없는 단점이 존재. 

현재는 두 번째 방법이 이용된것으로 보이며 부모로부터의 조인이 필요하여 부하 발생 & 속도 저하 그리고 복잡하기에 바꾸는게 나을꺼 같습니다. 
세 번째 방법의 경우 필드가 바뀌지 못하는 제한이 있어 적절하지 않은거 같습니다 (agent가 다른 필드를 가짐)  

현재 user 모델의 경우 abstractuser로부터 상속받기에 첫 번째 방법을 이용하기 위해 agent 모델도 abstractuser로부터 상속 받으니 문제가 발생했습니다. 따라서 abstractuse로부터 상속받는 abstract class를 만들고 이를 상속하는 user & agent를 만드는식으로 접근하고자 합니다.

**Comment by sanghunjo921** [comment]
저번 시간에 말씀해준데로 agent가 user를 가르키도록 수정했습니다.

현재 erd상으로 보면 contract모델의 경우 유저와 다대1 관계 (집이 여러개인 집주인의 경우 여러개의 property에 대한 계약을 가지므로) 에이전트와 다대1 관계를 이루고 있습니다. (에이전트가 여러명의 집주인/세입자의 계약을 도와주는 경우)

현재 고민점은
이전에는 contract모델이 유저와 에이전트 각 각 외래키를 가지고 있는데 수정한 에이전트의 경우 유저 모델을 가르키게 되기 때문에 contract모델이 유저 필드만 가지면 될꺼 같은데 (circular import issue 방지 ? ) 맞는 방향일까요?

**Comment by sanghunjo921** [comment]
일단은 어떤 에러가 발생할지 확인차 모델 수정후 migrations 새로 만들었는데 에러가 나서
showmigrations로 마이그레이션 체크 후 user, transaction, property 앱 모두 마이그레이션 헤제후 해당 앱의 migrations 폴더에서 기존 파일들 다 지우고 새로 마이그레이션은 만들었는데 migrate 할 때 에러가 발생하네요.

django.db.utils.OperationalError: table "transactions_agent" already exists

**Comment by sanghunjo921** [comment]
해결법 찾던중 --fake 이용하여 properties & transactions 앱에 migrate 적용했습니다.

**Comment by sanghunjo921** [comment]
> 1. Circular dependency가 없는 것으로 보이네요. 그냥 Agent와 User 각각에 디펜던시를 두는 것이 의미상으로도 맞을 것 같습니다.
> 
> ```
> Contract ---> Agent ---> User
>      |                     ^
>      ----------------------|
> ```
> 
>  2. 마이그레이션 파일을 바꾼다고 이미 DB에 적용되어 있는 변화가 사라지지는 않습니다. [공식 문서 해당 부분](https://docs.djangoproject.com/en/4.1/topics/migrations/#reversing-migrations)을 참조해서 마이그레이션을 revert한 뒤에 다시 마이그레이션하셔야 합니다. 개발 단계라서 DB를 날려버려도 되는 경우에는 sqlite3 파일을 제거해도 괜찮습니다.

옙 각각에 디펜더시를 두고 진행했어요!
